# Generated by Django 3.1.6 on 2021-02-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_dietsupplement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietSupplement',
        ),
    ]
